version: "3"
services: 
  listing-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
    image: mysql:5.7
  
  auth-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db
    image: mysql:5.7
  
  listing-service:
    build: "./listing-service"
    depends_on:
      - listing-service-db
    volumes:
      - "./listing-service:/opt/app"
  
  auth-service:
    build: "./auth-service"
    depends_on:
      - auth-service-db
    volumes:
      - "./auth-service:/opt/app"